### ISSUE TITLE
Changement du propriétaire de l'app

### ISSUE THREAD

**Issue by frju365** [YunoHost-Apps/monica_ynh#1]
Bonjour, 
Il serait bien, pour une meilleure gestion des applications et une meilleure gestion des contributions, que toutes les apps rejoignent l'organisation **Yunohost-Apps**.
Merci,
frju365
_____
Hello,
To manage in a better way the contributions and the Apps, we invite you to change the ownership of your app  to **Yunohost-Apps** Organization. 
Thanks,
frju365

**Comment by rndmh3ro** [comment]
Hey @frju365,

done, thanks!

Can you give me permissions/create a team for the repository?

**Comment by frju365** [comment]
Thanks :) 
I created a team(monica app) and I give you admin access to the repository and you are maintainer of the team. Done !
If you have any question, don't hesitate :)
frju365

**Comment by rndmh3ro** [comment]
Thanks, done!

**Comment by frju365** [comment]
Thanks !
frju365
