### ISSUE TITLE
Update to 1.4.1

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/monica_ynh#10]
Please update to version 0.7.1.

**Comment by rndmh3ro** [comment]
On it: https://ci-apps.yunohost.org/jenkins/job/monica%20(Community)/

**Comment by anmol26s** [comment]
Thanks

**Comment by anmol26s** [comment]
Please update to version [1.2.0](https://github.com/monicahq/monica/releases/tag/v1.2.0) which brings exciting new feature of task with check mark option.

**Comment by anmol26s** [comment]
Please update to version 1.3.0.

**Comment by anmol26s** [comment]
Please update to version 1.4.1. I think app will require to be reworked on as now account can be created while doing the installation.
