### ISSUE TITLE
Install Monica in a subdirectory or Subdomain

### ISSUE THREAD

**Issue by dosch** [YunoHost-Apps/monica_ynh#18]
Right now Monica can only be the only app in Yunohost.

Seems related to this: 
https://github.com/monicahq/monica/issues/139

**Comment by anmol26s** [comment]
Yes this issue is known and there is a link to it in the readme too.
Will have to test this. Don't expect this feature to be implemented soon for the app.

**Comment by dosch** [comment]
OK, will patiently await. If you need testers, let me know

**Comment by croulibri** [comment]
I have installed in a subdirectory and it works well, it seems only subdirectory doesn't work.

**Comment by croulibri** [comment]
Oups... my mistake
I have installed in a _subdomain_ and it works well, it seems only subdirectory doesn't work.
So you can have other yunohost apps, but on different subdomains that the one Monica uses.

**Comment by anmol26s** [comment]
sorry to say, I still don't understand what you want to do. Subdomain works, but you will not find the option on Yunohost Monica package to install over sub-directory because its has not been implemented by upstream.

**Comment by croulibri** [comment]
Sorry for not being clear.
My only point was to say that install on subdomain is working, I felt that was the question of this topic "_Install Monica in a subdirectory or Subdomain_"

So unlike @dosch  is saying , you can have different apps on your yunohost  server as long as other apps are located in a different subdomain that Monica's one.
