### ISSUE TITLE
Version behind.

### ISSUE THREAD

**Issue by dosch** [YunoHost-Apps/monica_ynh#19]
Monica is on version 2.3

The app in Yunohost is on 2.1.1

**Comment by anmol26s** [comment]
How did you check this?
The sources are pointing to 2.3
https://github.com/YunoHost-Apps/monica_ynh/blob/master/conf/app.src#L1

**Comment by dosch** [comment]
Indeed now it does. I installed it a week ago and then it was 2.1.1.
Now it is indeed updated
