### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/monica_ynh#2]
Hi
As mentioned in the forum https://forum.yunohost.org/t/monica-personal-relationship-manager-a-new-kind-of-crm-to-organize-interactions-with-your-friends-and-family/3041/10?u=kanhu , the installation fails.
```

+ sudo /usr/bin/php7.0 /var/www/monica/composer.phar install --no-dev --prefer-dist -d /var/www/monica --quiet --no-interaction
Warning: Your requirements could not be resolved to an installable set of packages.
+ ynh_die 'Unable to update monica core dependencies'
+ echo 'Unable to update monica core dependencies'
+ exit 1
Warning: Unable to update monica core dependencies
```

**Comment by rndmh3ro** [comment]
That is now hopefully fixed by https://github.com/YunoHost-Apps/monica_ynh/commit/02e4c78b14d79f9c75113a2383aaead786eac24a.
Can you try again?

Thanks for reporting here!

**Comment by anmol26s** [comment]
I can install now. But what is the password for my account. The installation did not ask for a password and the user password used for YunoHost login don't work. I have to reset the password from mail.

The mail I got for password reset has the domain name two times. eg. domain_monica.tld/domain_monica.tld//password/rest/some_large_number.
Is it a monica bug or package issue ?

**Comment by rndmh3ro** [comment]
The default password is `admin` (its in the readme) as there's no way yet to use existing yunohost accounts.

As for the mail, I'll have to take a look. Would you mind creating a new issue for that?
