### ISSUE TITLE
Don't run nodejs

### ISSUE THREAD

**Issue by asbiin** [YunoHost-Apps/monica_ynh#20]
Hello
I saw in the install script you install and run nodejs.
This is not needed by Monica installation, it's only needed on development state.
You should consider remove it.

**Comment by asbiin** [comment]
See https://github.com/YunoHost-Apps/monica_ynh/blob/master/scripts/install#L137

**Comment by anmol26s** [comment]
Thanks for helping in improvement of the package.
Fixed https://github.com/YunoHost-Apps/monica_ynh/commit/8e9beb5a148a08be531c91e3852346caf7ead964
