### ISSUE TITLE
Use 'monica:update' command 

### ISSUE THREAD

**Issue by asbiin** [YunoHost-Apps/monica_ynh#21]
# In the installation script
You can be replaced by `monica:update` command.
```
# setup application config
cd $final_path && sudo /usr/bin/php7.1 artisan config:clear
cd $final_path && sudo /usr/bin/php7.1 artisan -q migrate --force
cd $final_path && sudo /usr/bin/php7.1 artisan -q storage:link
cd $final_path && sudo /usr/bin/php7.1 artisan -q setup:production --force
```
https://github.com/YunoHost-Apps/monica_ynh/blob/master/scripts/install#L142
`monica:update` command does exactly the same job, and more.

# In the upgrade script
```
cd $final_path && sudo /usr/bin/php7.1 artisan migrate --force
```
https://github.com/YunoHost-Apps/monica_ynh/blob/master/scripts/upgrade#L117
You should run `monica:update` command because it runs not only the migration, but other script an upgrade should do.

**Comment by anmol26s** [comment]
Thank for helping. Is there need to backup any directory in the main folder while update is done like cache or profile picture,etc. The upgrade script removes the Monica directory complete and reinstall the new version.
Fixed https://github.com/YunoHost-Apps/monica_ynh/commit/8e9beb5a148a08be531c91e3852346caf7ead964

**Comment by anmol26s** [comment]
Further questions :). Can the php7.0 be used instead of php7.1 ?

**Comment by asbiin** [comment]
@anmol26s We depend on Laravel 5.6, which need php >= 7.1, so : non, php7.0 can't be used.
Url can be changed, you will just need to update APP_URL environment variable (in .env file), to make generated mails use the right address.

**Comment by anmol26s** [comment]
@asbiin 
The APP_URL is used as localhost see here https://github.com/YunoHost-Apps/monica_ynh/blob/master/conf/.env#L21 because of this issue https://github.com/YunoHost-Apps/monica_ynh/issues/3
