### ISSUE TITLE
Broken Yunohost following failed upgrade to 2.4.2.

### ISSUE THREAD

**Issue by croulibri** [YunoHost-Apps/monica_ynh#23]
This morning I tried to update Monica through Yunohost web interface.
I got the following result :
```
The app was restored to the way it was before the failed upgrade.

shell-init : erreur de détermination du répertoire actuel : getcwd : ne peut accéder aux répertoires parents : Aucun fichier ou dossier de ce type

update-alternatives: avertissement: forçage de la réinstallation de l'alternative /usr/bin/php7.0 car le groupe de liens php est cassé

dpkg-preconfigure: impossible de réouvrir stdin :

debconf: Utilisation de l'interface Teletype en remplacement

debconf: (Cette interface a besoin d'un terminal de contrôle.)

debconf: Impossible d'initialiser l'interface : Readline

debconf: Utilisation de l'interface Readline en remplacement

debconf: (L'interface dialog ne fonctionnera pas avec un terminal rustique (« dumb »), un tampon shell d'Emacs ou sans terminal de contrôle.)

debconf: Impossible d'initialiser l'interface : Dialog

shell-init : erreur de détermination du répertoire actuel : getcwd : ne peut accéder aux répertoires parents : Aucun fichier ou dossier de ce type

shell-init : erreur de détermination du répertoire actuel : getcwd : ne peut accéder aux répertoires parents : Aucun fichier ou dossier de ce type

shell-init : erreur de détermination du répertoire actuel : getcwd : ne peut accéder aux répertoires parents : Aucun fichier ou dossier de ce type

shell-init : erreur de détermination du répertoire actuel : getcwd : ne peut accéder aux répertoires parents : Aucun fichier ou dossier de ce type

shell-init : erreur de détermination du répertoire actuel : getcwd : ne peut accéder aux répertoires parents : Aucun fichier ou dossier de ce type

shell-init : erreur de détermination du répertoire actuel : getcwd : ne peut accéder aux répertoires parents : Aucun fichier ou dossier de ce type

shell-init : erreur de détermination du répertoire actuel : getcwd : ne peut accéder aux répertoires parents : Aucun fichier ou dossier de ce type

shell-init : erreur de détermination du répertoire actuel : getcwd : ne peut accéder aux répertoires parents : Aucun fichier ou dossier de ce type

shell-init : erreur de détermination du répertoire actuel : getcwd : ne peut accéder aux répertoires parents : Aucun fichier ou dossier de ce type

shell-init : erreur de détermination du répertoire actuel : getcwd : ne peut accéder aux répertoires parents : Aucun fichier ou dossier de ce type

shell-init : erreur de détermination du répertoire actuel : getcwd : ne peut accéder aux répertoires parents : Aucun fichier ou dossier de ce type

shell-init : erreur de détermination du répertoire actuel : getcwd : ne peut accéder aux répertoires parents : Aucun fichier ou dossier de ce type

shell-init : erreur de détermination du répertoire actuel : getcwd : ne peut accéder aux répertoires parents : Aucun fichier ou dossier de ce type

Remove the user monica

Removing database monica

Upgrade failed.

!!

monica's script has encountered an error. Its execution was cancelled.

!!

Le service de mail Dovecot doit être démarré, si vous souhaitez voir l'espace disque occupé par la messagerie

2018-07-30 10:44:31 URL:https://codeload.github.com/monicahq/monica/zip/v2.4.2 [3374607] -> "v2.4.2.zip" [1]

Mise à jour de l'application monica...

Upgrading apps monica
```

FYI, Dovecot is not activated because I am not using Yunohost email system.

Then, after that failed upgrade, some other apps could'nt start, such as Nextcloud which tell me php7 was not loaded properly.

Finally, I had the bad idea to restart my server... and of course I can't access anymore to my Yunohost server through web interface :-(
It seems Yunohost server coudn't start properly as I can't connect to xmpp or synapse

I will try tonight at home to connect through ssh (I can't now) and identify what is broken, probably php config.

If you have any idea about what to do to bring up my yunohost server, you are most welcome !

**Comment by anmol26s** [comment]
I hope you can login to the ssh. Check if yunohost is installed. Check if php7.0 and php7.1 is installed. Then check if nginx is not giving the error.

**Comment by croulibri** [comment]
I had the same problem as at https://forum.yunohost.org/t/le-service-nginx-ne-se-lance-plus/5152/8
Is Monica installing or activating apache ?
In the process, I have lost Monica app with all my data, it seems.
When upgrading, is Monica doing any backup ? I don't see any :-(

**Comment by anmol26s** [comment]
I am not able to reproduce the error on my server. The update is going fine for me.
Can you please install the monica on other domain like monica1.domain.tld for testing purpose and see if it gets installed correctly without errors? Monica is multi-instance, so it can install on multiple times on your server. 

Keep the backup safe and copy it at some other place. It has your data with previous version, loosing it will result in losing your data.

**Comment by anmol26s** [comment]
I have updated the testing branch. Can you check if the problem gets resolved.

Upgrade:
`$ yunohost app upgrade -u https://github.com/YunoHost-Apps/monica_ynh monica`

**Comment by croulibri** [comment]
I finally could try to upgrade again and it is now working perfectly. 

Thanks @anmol26s for your support and sorry for being so late in answering your previous message.
