### ISSUE TITLE
Update to 2.5.0 does not show in Webinterface Yunohost

### ISSUE THREAD

**Issue by dosch** [YunoHost-Apps/monica_ynh#24]
Hey, I saw you already updated Monica to 2.5.0 (THNX!) 
But the update does not show when I ask my yunohost to check for updates

**Comment by anmol26s** [comment]
That is weird. You should ask about it on the forum and check if this is only related to Monica or other apps too. This can happen if the app update checker is failing or having problem. 

Meanwhile you can update with the following command : 

`yunohost app upgrade -u https://github.com/YunoHost-Apps/monica_ynh monica`

**Comment by dosch** [comment]
Thnx for the fast response. 
IT is now solved 

(I had some locale issues that are unrelated, but prevented this app from upgrading)
