### ISSUE TITLE
2.7.1 is out

### ISSUE THREAD

**Issue by dosch** [YunoHost-Apps/monica_ynh#26]
@anmol26s Care to update?

(if I can help in this someway, let me know)

**Comment by anmol26s** [comment]
Hi
The app has been updated to version **2.7.1**.

You can help by spreading the word on social media and blogs about Monica and Yunohost so that someone who want similar solution for himself can know about it.

**Comment by dosch** [comment]
Yeah, still have to find the time to do that. It does not work out of the box for sure...

**Comment by dosch** [comment]
> And maybe test the Android app again with the installed instance in your free time. It would nice if the Android application issue gets resolved.

![screenshot_monica_20180925-094500](https://user-images.githubusercontent.com/5372610/46000605-5aca1800-c0a9-11e8-8b9a-7051f9bcfd45.png)

@anmol26s No luck so far...

**Comment by anmol26s** [comment]
@dosch 
:tada: 
![image](https://user-images.githubusercontent.com/5068843/46565687-a7c2af80-c92f-11e8-81eb-4e50dbdcde27.png)

**Comment by dosch** [comment]
nice! You made it work! 
I am still unable to get it going.... :-(

Any tips?

**Comment by anmol26s** [comment]
If you have previously tried to implement keys for the android app, the upgrade script would not create new keys.
You will have to remove keys under /var/www/monica/storage. After which update your app which will create new keys and set proper values in .env by itself. Then try to login from the app and it should work.

**Comment by dosch** [comment]
I did not have to delete keys. Simply upgrading to 2.8.1 did the trick!
Thnx!

**Comment by anmol26s** [comment]
Great to know, it work.

**Comment by dosch** [comment]
something else broke... but hey, you gain some, you loose some I guess ;-)
https://github.com/monicahq/monica/issues/1906#issuecomment-429010750

**Comment by anmol26s** [comment]
@dosch 
Can you do : 

`$ cd /var/www/monic && /usr/bin/php7.1 artisan monica:update --force`
and then 
`$ chown -R monica:monica /var/www/monica`

**Comment by dosch** [comment]
I just ran

```
sudo yunohost app upgrade -u https://github.com/YunoHost-Apps/monica_ynh monica
```

**Comment by dosch** [comment]
Sure.

```
$ cd /var/www/monica/ && /var/www/monica$ /usr/bin/php7.1 artisan monica:update --force
✓ Maintenance mode: on
✓ Resetting application cache
✓ Clear config cache
✓ Clear route cache
✓ Clear view cache
✓ Performing migrations
✓ Ping for new version
✓ Maintenance mode: off
Monica v2.8.1 is set up, enjoy.
```

```
/var/www/monica$ sudo chown -R monica:monica /var/www/monica
/var/www/monica$ 
```

Nothing has changed tough... same error still there

**Comment by anmol26s** [comment]
This is weird. Maybe clear the cache of browser? 
I am trying to reproduce it. But unable to do it.

**Comment by anmol26s** [comment]
What the response on moblie ? Can you see the contacts on mobile?

**Comment by dosch** [comment]
Clearing cache didn't help. And yes, I can see the contacts on the app

**Comment by dosch** [comment]
Shall I create a new issue for this?

**Comment by anmol26s** [comment]
If you have backup of the app you can restore that app and see if the app works as before and then try to upgrade again.

You can try two things first for investigation.
1. The app is multi-instace so you can try to install another monica app instance on other domain on your server and test if the new instance work adding contacts. As long as you have backup you have the sql backup and all your contacts are present there.
2. As mentioned in the monica main issue page you opened, provide the error log that the best way to investigation. If I have get where the error coming from then I can fix it. As the upgrade updates the table with no error, I am not getting where the error is coming from.

**Comment by dosch** [comment]
Thnx for the extra info! 

In the main issue page they mentioned a .env file I need to change to log issues. Can you help me to locate this in my yunohost install? I have no experience with this...

**Comment by anmol26s** [comment]
I think Monica use SENTRY for logs. But I don't have any Idea about how to use it and there is no documents
You should open an issue about how to use it. It will help other users too.
Meanwhile I have updated the app to 2.9.0.

**Comment by dosch** [comment]
> The app is multi-instace so you can try to install another monica app instance on other domain on your server and test if the new instance work adding contacts. As long as you have backup you have the sql backup and all your contacts are present there.

I am not sure I can install the same app twice in Yunohost. 

![screenshot 2018-10-18 at 11 10 46](https://user-images.githubusercontent.com/5372610/47143895-7d290d00-d2c6-11e8-8c8d-11516fde0945.png)

**Comment by dosch** [comment]
Basically the one mentioned above in the screenshot. 
Yunhost encounters an internal error.

**Comment by anmol26s** [comment]
Can you try to install from command line?
