### ISSUE TITLE
2.12 is out !

### ISSUE THREAD

**Issue by croulibri** [YunoHost-Apps/monica_ynh#29]
Hello,

I noticed that the new version of Monica is out for (only) 11 days...
I have read that CardDav is finally available out of Beta, I am interested to test it!

Would you be able to update Monica?

Thanks in advance for your great work of maintaining this yunohost app

**Comment by anmol26s** [comment]
I have not tested the cardDav. I have updated it. But it should work now. I will test.

**Comment by croulibri** [comment]
I've just try the 2.12 version.
CaldDAV seems to work well, it's great !

But when I am an on the page of M. X, I create an activity that I shared with him. I can create an activity and specify the type, the date,... but if I want to add another participant, then the widows somehow "crash" and I come back to the welcome page of Monica.
So I can create new activities but I can't add participants to them.

Do you have also this issue ?

**Comment by anmol26s** [comment]
Can you explain the issue in more details? I will test it tomorrow.

**Comment by croulibri** [comment]
Create a new activity with your friend John
Specify the type, the date,... validate to save the newly created activity. No problem, the activity is created with all characteristics.

Now, create a new activity with your friend Marc.
Specify the type, the date,... No problem.
Try to add a participant (who was involved ?) to this activity, because Sarah was also there. When you add Sarah to the activity, then the page of "Activity creation" is suddenly closed and you are back at the "welcome page" of Monica. Your new activity with Marc and Sarah has not been created.

Am I clear ?
but if I want to add another participant, then the widows somehow "crash" and I come back to the welcome page of Monica.
So I can create new activities but I can't add participants to them.

**Comment by croulibri** [comment]
Thanks @anmol26s for the testing branch update.
I have made few tests and it seems everything is working !
