### ISSUE TITLE
Yunohost update impossible due to sury.org repository

### ISSUE THREAD

**Issue by croulibri** [YunoHost-Apps/monica_ynh#31]
Hello,

I can't update any more my Yunohost instance due to error with the https://packages.sury.org (similar as https://forum.yunohost.org/t/internal-error-system-update/7458/4)

If I look at the list of app that use this repository in my server, only Monica is concerned.

Could you advice me on how to solve this problem without undermining the future update of Monica ?

Thanks !

**Comment by croulibri** [comment]
The post explaining the problem of the key of the  https://packages.sury.org repository is at https://www.patreon.com/posts/25451165
In short, to update the APT signing key, you can download the new key from the respective repositories, f.e. for the PHP, you would do:
    `wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg`

Should the install or update script be updated ?

**Comment by yalh76** [comment]
Already solved
