### ISSUE TITLE
Monica 2.16 available

### ISSUE THREAD

**Issue by nr458h** [YunoHost-Apps/monica_ynh#38]
Hi @anmol26s,

any chance to get an update as we are 4 realeses behind.

Would love to see an update.

Thanks in advance ♥️

**Comment by Dadourlou** [comment]
Or maybe our lovely dev @asbiin ? <3

**Comment by visika** [comment]
2.17.0 Available. It's gotten a lot of useful features and corrections since 2.14.

**Comment by anmol26s** [comment]
Will update it next.

**Comment by nr458h** [comment]
As we are already on 2.17 I close this issue.
Huge thanks for the work!
