### ISSUE TITLE
[buster] Adapt the PHP 7.x custom install / requirement

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/monica_ynh#39]
Following the discussion started [here](https://github.com/YunoHost/issues/issues/1255#issuecomment-596254890), this app needs to be adapted both to : 
- be installable on a fresh Buster system
- make the transition smooth for people upgrading from Stretch to Buster

Currently the app relies on a custom install of PHP 7.1 / 7.2 / 7.3 which should be adapted. Imho (to be discussed and see with other app packagers after we gain more XP with this) : 
- the scripts should be adapted to use PHP 7.3 instead of 7.2
- the upgrade script should take care of the move from 7.2 to 7.3 (which for users could and should therefore happen prior to the upgrade to buster)
- we should have an if/else to install PHP 7.3 only if we're on stretch (and not on buster) [like drafted here for mastodon](https://github.com/YunoHost-Apps/pixelfed_ynh/pull/101/commits/c2f96cf3dc743ad1963926d8cd84981d59e5b816) but also need to be propagated on restore script (and maybe upgrade script)

Overall this treatment should be pretty much the same for all apps in that situation, so once we solve this for one app it should be easily applicable to other similar apps.

**Comment by yalh76** [comment]
Already solved
