### ISSUE TITLE
No longer maintained - time to lose the `Maintained` tag?

### ISSUE THREAD

**Issue by gisforgabriel** [YunoHost-Apps/monica_ynh#50]
@yalh76 Maybe this should lose the `Maintained` tag on [README.md](https://github.com/YunoHost-Apps/monica_ynh/blob/master/README.md)? There have been a dozen versions, including a major version, released and well over a year has passed since the version of Monica this uses was released.

**Comment by yalh76** [comment]
you should do a PR on https://github.com/YunoHost/apps/blob/master/apps.json to make it no maintained ...

**Comment by gisforgabriel** [comment]
Done 👍 - https://github.com/YunoHost/apps/pull/1207

I didn't know if there was an official process that you go through before changing an app's status.

If you are happy with that, I'll close this issue.

**Comment by 4abhinavjain** [comment]
Any plans to upgrade and maintain the app in the future? I recently discovered Monicahq and I think it is a unique and useful app.

**Comment by yalh76** [comment]
> 
> 
> Done 👍 - [YunoHost/apps#1207](https://github.com/YunoHost/apps/pull/1207)
> 
> I didn't know if there was an official process that you go through before changing an app's status.
> 
> If you are happy with that, I'll close this issue.

merged ^^

**Comment by yalh76** [comment]
> 
> 
> Any plans to upgrade and maintain the app in the future? I recently discovered Monicahq and I think it is a unique and useful app.

You should try to make a PR to upgrade it, if you need help, you can contact the 
Matrix : #yunohost-apps:matrix.org
