### ISSUE TITLE
Installation fails - status set to notworking in one week

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost-Apps/monica_ynh#8]
Hello @rndmh3ro,

Your app failed to install on our CI, hence it will be set at notworking status in one week unless installation is fixed.

You can find the complete log here
https://ci-apps.yunohost.org/jenkins/job/monica%20(Community)/6/consoleFull

Don't hesitate to join our Apps packaging room on XMPP (apps@conference.yunohost.org) for help!

The YunoHost Apps Group

**Comment by rndmh3ro** [comment]
I completely revamped the installation, removal, backup and restore scripts, according to latest yunohost standards.
Most of it looks fine, except for the `incorrect_path` check. It fails with `Error: yunohost cli - Invalid choice for argument 'path', it must be one of /`

Can you explain, what this check does and why it does fail?
I don not understand this from the documentation.

**Comment by JimboJoe** [comment]
Hi,
this test tries to install the application with a "malformed" URL: with the default `check_process` file, it tries to install with path `path/`.
In your case, your manifest restricts [here](https://github.com/YunoHost-Apps/monica_ynh/blob/master/manifest.json#L44) path entries to only `/`. So, as package_check tries to install with path `path/`, it fails with the error message `Invalid choice for argument 'path', it must be one of /`.
Thus, as your package can only install at domain root, you should disable that test in your `check_process` file.

By the way, by just reading your install script, you should use `ynh_install_app_dependencies` helper [here](https://github.com/YunoHost-Apps/monica_ynh/blob/master/scripts/install#L73). It would allow to remove your (heavy!) added dependencies when removing package. You already used the right helper in the `remove` script [here](https://github.com/YunoHost-Apps/monica_ynh/blob/master/scripts/remove#L39).

Anyway, good job, this issue can be closed! 😉

**Comment by rndmh3ro** [comment]
Thanks for your help!

**Comment by JimboJoe** [comment]
Latest CI results lead to a notworking application: https://ci-apps.yunohost.org/jenkins/job/monica%20(Community)/24/consoleFull
Status will be changed to notworking in one week unless installation is fixed.
Good luck 😉

**Comment by maniackcrudelis** [comment]
Hi,

Your app doesn't work on our CI and is currently level 0.
https://github.com/YunoHost-Apps/monica_ynh/issues/8

Your app will be moved at 'notworking' status by the end of this week, on May, 27 if nothing is done before to make it work.

**Comment by anmol26s** [comment]
It should work now.

**Comment by maniackcrudelis** [comment]
Still broken.
```
Your requirements could not be resolved to an installable set of packages.                                    
Unable to update monica core dependencies
```

**Comment by maniackcrudelis** [comment]
I ran package check on a VM with the last version of this package.
